[versions]
appVersion = "1000"
compileSdkVersion = "33"
minSdkVersion = "16"
composeMinSdkVersion = "21"
targetSdkVersion = "33"
agp = "8.0.2"
kotlin = "1.8.20"
appcompat = "1.6.1"
constraintLayout = "2.1.4"
junit4 = "4.13.2"
androidTestJUnit = "1.1.5"
androidTestRules = "1.5.0"
androidTestEspresso = "3.5.1"
recyclerView = "1.3.1"
compose = "1.4.6"
lifecycle = "2.6.1"
coroutines = "1.7.1"
fragment = "1.6.0"
androidxComposeBom = "2023.05.01"
composeActivity = "1.7.1"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "androidTestEspresso" }
androidTestJUnit = { group = "androidx.test.ext", name = "junit", version.ref = "androidTestJUnit" }
androidTestRules = { group = "androidx.test", name = "rules", version.ref = "androidTestRules" }
androidTestEspresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidTestEspresso" }
recyclerView = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerView" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-viewModel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-compose-material = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActivity" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
